export const AWS_S3_IMPORT_BUCKET_REGION =
  process.env.AWS_S3_IMPORT_BUCKET_REGION || '';
export const AWS_S3_IMPORT_BUCKET_NAME = process.env.AWS_S3_IMPORT_BUCKET_NAME;
export const AWS_SQS_CATALOG_ITEMS_QUEUE_URL =
  process.env.AWS_SQS_CATALOG_ITEMS_QUEUE_URL;
