openapi: '3.0.1'
info:
  title: 'shared-http-api'
  version: '2026-04-29 11:22:27UTC'
servers:
  - url: 'https://h8j8j6pg2c.execute-api.eu-central-1.amazonaws.com'
tags:
  - name: Products
    description: Product operations

paths:
  /products:
    get:
      summary: 'Get list of products'
      tags:
        - Products
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: 'Create Product'
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductDto'
      responses:
        '201':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProductDto'

  /products/{productId}:
    get:
      summary: 'Get product by id'
      tags:
        - Products
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: 'Product not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
        - name: 'productId'
          in: 'path'
          description: 'Generated path parameter for productId'
          required: true
          schema:
            type: 'string'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - description
        - price
        - count
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number

    CreateProductDto:
      type: object
      required:
        - title
        - description
        - price
        - count
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
